# ==============================================================================
# CHAOSLIB - Modular Build System
# ==============================================================================

# Include user configurations (defines, build type, enabled modules)
include config.mk

# ------------------------------------------------------------------------------
# DIRECTORIES
# --------------------------------0----------------------------------------------
BUILD_DIR := build
OBJ_DIR   := $(BUILD_DIR)/obj
LIB_DIR   := $(BUILD_DIR)/lib
FINAL_LIB := $(LIB_DIR)/libchaoslib.a

# ------------------------------------------------------------------------------
# MODULE SELECTION
# These modules are always compiled
# ------------------------------------------------------------------------------
SELECTED_MODULES := chaos_core chaos_types chaos_platform chaos_memory

# Conditional inclusion based on config.mk variables
ifeq ($(CHAOS_ENABLE_ALLOC), 1)
    SELECTED_MODULES += chaos_alloc
endif

ifeq ($(CHAOS_ENABLE_FLOAT), 1)
    SELECTED_MODULES += chaos_math
endif

# Including string and std
SELECTED_MODULES += chaos_string chaos_std

# ------------------------------------------------------------------------------
# COMPILER & ARCHIVER FLAGS
# ------------------------------------------------------------------------------
CFLAGS_BASE := \
    -std=$(C_STANDARD) \
    -ffreestanding \
    -fno-builtin \
    $(WARNINGS) \
    -MMD -MP # Generate dependency files (.d) for header tracking

# Select optimization level based on BUILD_TYPE
ifeq ($(BUILD_TYPE),debug)
    CFLAGS_OPT := $(OPT_DEBUG)
else ifeq ($(BUILD_TYPE),release)
    CFLAGS_OPT := $(OPT_RELEASE)
else ifeq ($(BUILD_TYPE),size)
    CFLAGS_OPT := $(OPT_SIZE)
else
    CFLAGS_OPT := -O2
endif

# Combine everything
CFLAGS := $(CFLAGS_BASE) $(CFLAGS_OPT)

# Map config.mk variables to C Preprocessor defines
DEFINES := \
    -DCHAOS_ENABLE_ASSERT=$(CHAOS_ENABLE_ASSERT) \
    -DCHAOS_ENABLE_ALLOC=$(CHAOS_ENABLE_ALLOC) \
    -DCHAOS_ENABLE_LOG=$(CHAOS_ENABLE_LOG) \
    -DCHAOS_ENABLE_FLOAT=$(CHAOS_ENABLE_FLOAT) \
	-DCHAOS_ENABLE_INT64=$(CHAOS_ENABLE_INT64) \
	-DCHAOS_STRICT_ABI_CHECK=$(CHAOS_STRICT_ABI_CHECK)

# Automatically include 'inc/' folders of all active modules
INC_FLAGS := $(foreach mod,$(SELECTED_MODULES),-I$(mod)/inc)

# ------------------------------------------------------------------------------
# SOURCE & OBJECT DISCOVERY
# ------------------------------------------------------------------------------

# This function creates a list of object files prefixed by their module name
# Example: chaos_core/src/chaos_core.c -> build/obj/chaos_core_chaos_core.o
define get_objs
$(patsubst $1/src/%.c,$(OBJ_DIR)/$1_%.o,$(wildcard $1/src/*.c))
endef

# Collect all objects from all selected modules
ALL_OBJS := $(foreach mod,$(SELECTED_MODULES),$(call get_objs,$(mod)))
# Collect dependency files generated by -MMD
ALL_DEPS := $(ALL_OBJS:.o=.d)

# ------------------------------------------------------------------------------
# BUILD RULES
# ------------------------------------------------------------------------------

.PHONY: all clean info size asm

# Default target
all: $(FINAL_LIB)

# Link all objects into a single static library
$(FINAL_LIB): $(ALL_OBJS)
	@echo "Creating library archive: $@"
	@mkdir -p $(LIB_DIR)
	$(AR) rcs $@ $^

# Template rule to compile .c files from each module
# The use of 'eval' allows us to handle multiple source directories
define compile_rule
$(OBJ_DIR)/$1_%.o: $1/src/%.c
	@mkdir -p $$(OBJ_DIR)
	@echo "Compiling [$1]: $$<"
	$(CC) $(CFLAGS) $(DEFINES) $(INC_FLAGS) -c $$< -o $$@
endef

# Generate compilation rules for every active module
$(foreach mod,$(SELECTED_MODULES),$(eval $(call compile_rule,$(mod))))

# Include dependency files (keeps track of changes in .h files)
-include $(ALL_DEPS)

# ------------------------------------------------------------------------------
# TOOLS & UTILITIES
# ------------------------------------------------------------------------------

# Show size of the final library
size: $(FINAL_LIB)
	$(SIZE) $(FINAL_LIB)

# Generate assembly files for debugging/optimization analysis
asm: $(ALL_OBJS)
	$(foreach obj,$(ALL_OBJS),$(OBJDUMP) -d $(obj) > $(obj:.o=.asm);)

# Print build configuration
info:
	@echo "--- CHAOSLIB BUILD INFO ---"
	@echo "Selected Modules: $(SELECTED_MODULES)"
	@echo "Build Type:       $(BUILD_TYPE)"
	@echo "Compiler:         $(CC)"
	@echo "Library Path:     $(FINAL_LIB)"

# Clean build artifacts
clean:
	@echo "Cleaning build directory..."
	rm -rf $(BUILD_DIR)